### ISSUE TITLE
Error occurred during startup, unable to update access token.

### ISSUE THREAD

**Issue by dengchangdong** [acheong08/ChatGPT-to-API#102]
he specific error message is as follows:

```
Location: begin
Status code: 0
Details:
Embedded error: Get "https://chat.openai.com/api/auth/csrf": x509: certificate signed by unknown authority
```

Could you please advise on how to resolve this? Thank you!

**Comment by someway22** [comment]
safe here

**Comment by dengchangdong** [comment]
已通过[Golang 发送 Https 请求报错 `x509 certificate signed by unknown authority` (在 Docker 中运行)](https://www.ono.lol/2020/09/11/ComputerScience/Golang/Golang%20%E5%8F%91%E9%80%81%20Https%20%E8%AF%B7%E6%B1%82%E6%8A%A5%E9%94%99%20x509%20certificate%20signed%20by%20unknown%20authority/)这篇文章解决这个问题。
过程如下：
1、下载`https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt`，重命名为`ca-certificates.crt`并复制到`ChatGPT-to-API`根目录。
2、修改`Dockerfile`，在`COPY --from=builder /app/ChatGPT-To-API /app/ChatGPT-To-API`前面增加`COPY ./ca-certificates.crt /etc/ssl/certs/`
3、重构容器。
