### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by cateyelow** [acheong08/ChatGPT-to-API#11]
I'm posting it because I can't solve it.
I didn't know how to use authenticator due to how to insert proxies.txt, so i insert acces_tokens.json manually
[docker-compose-yml] is default
[Dockerfile] is default
[OS] Windows11

PS D:\ChatGPT-proxy\ChatGPT-to-API> docker logs chatgpttoapi
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
[GIN-debug] PATCH  /admin/puid               --> main.puidHandler (5 handlers)
[GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
[GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (6 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> main.nightmare (4 handlers)
2023/04/25 04:33:21 1 127.0.0.1:8080

PS D:\ChatGPT-proxy\ChatGPT-to-API> docker inspect chatgpttoapi
[
    {
        "Id": "ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547",
        "Created": "2023-04-25T04:33:20.603260485Z",
        "Path": "./ChatGPT-To-API",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 19656,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-04-25T04:33:21.059680436Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:4da18b68d6e7259a67f3c33960c1a2033935a96b24c20e67f6499de158dff7af",
        "ResolvConfPath": "/var/lib/docker/containers/ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547/hostname",
        "HostsPath": "/var/lib/docker/containers/ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547/hosts",
        "LogPath": "/var/lib/docker/containers/ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547/ec1065a50a4c98bf1222cc944a24cf2b09be7a6ba3b787d09c0c204dcc08f547-json.log",
        "Name": "/chatgpttoapi",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                27,
                120
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/2aceeab341dea9e67687171a6c9d1f73cb52765614c1b74636bd91ea2a5e7aab-init/diff:/var/lib/docker/overlay2/w3aiwqctn2wjhabqfhbh922ba/diff:/var/lib/docker/overlay2/onklsdxdkoh11tke7kca0s0bl/diff",
                "MergedDir": "/var/lib/docker/overlay2/2aceeab341dea9e67687171a6c9d1f73cb52765614c1b74636bd91ea2a5e7aab/merged",
                "UpperDir": "/var/lib/docker/overlay2/2aceeab341dea9e67687171a6c9d1f73cb52765614c1b74636bd91ea2a5e7aab/diff",
                "WorkDir": "/var/lib/docker/overlay2/2aceeab341dea9e67687171a6c9d1f73cb52765614c1b74636bd91ea2a5e7aab/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "ec1065a50a4c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "./ChatGPT-To-API"
            ],
            "Image": "chatgpt-to-api",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "be152ea2ca354fb6752ecf0af4c9ff98e6832f50a5e59da8a7fe90f777acf0f5",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/be152ea2ca35",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "8b22d2cb097cf13cbdb83df6a0f4fee1dca16e7d4c595448a1e738b88e38bc37",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "bead5a5db15ba990f9ec3ff9df6c54b4bf8def4925c7a49fd5657174a0a332e9",
                    "EndpointID": "8b22d2cb097cf13cbdb83df6a0f4fee1dca16e7d4c595448a1e738b88e38bc37",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

PS D:\ChatGPT-proxy\ChatGPT-to-API> docker ps
CONTAINER ID   IMAGE            COMMAND              CREATED         STATUS         PORTS                      NAMES
f5d30e7d2f50   chatgpt-to-api   "./ChatGPT-To-API"   2 minutes ago   Up 2 minutes   127.0.0.1:8080->8080/tcp   chatgpttoapi

**Comment by cateyelow** [comment]
I found the problem, window11 incompatible that using endless in golang
you should build on linux

**Comment by cateyelow** [comment]
but still i don't know how to use auto authenticator, it stucks on print id, pw

**Comment by acheong08** [comment]
> but still i don't know how to use auto authenticator, it stucks on print id, pw

Need whitelisted IP and need up update OpenAIAuth
