### ISSUE TITLE
docker部署的请问如何配置账号信息，使其自动获取access token？

### ISSUE THREAD

**Issue by walkchen9** [acheong08/ChatGPT-to-API#112]
vpn现在不允许登录，无法通过本地登录获取token了。

国外vps使用docker部署了该项目，如何配置账号信息，使其自动获取token？

**Comment by dengchangdong** [comment]
`docker-compose.yml` 文件增加下面的配置：
```
    volumes:
      - /宿主机路径/accounts.txt:/app/accounts.txt #配置账号密码（格式：账号:密码，一行一个）
      - /宿主机路径/api_keys.txt:/app/api_keys.txt #自定义的Key
      - /宿主机路径/access_tokens.json:/app/access_tokens.json #这个文件是一个空文件，部署的时候会自动添加accesstoken
```

**Comment by walkchen9** [comment]
open chat.openai.com.har: no such file or directory
Updating access token for *@abc.com
Location: begin
Status code: 0
Details: 
Embedded error: Get "https://chat.openai.com/api/auth/csrf": x509: certificate signed by unknown authority
2023/08/09 11:28:51 1 0.0.0.0:8080
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)


log显示这个错误，是证书错误 ？

**Comment by dengchangdong** [comment]
解决方法 [Issue #102](https://github.com/acheong08/ChatGPT-to-API/issues/102)

**Comment by walkchen9** [comment]
> 解决方法 [Issue #102](https://github.com/acheong08/ChatGPT-to-API/issues/102)

已解决，非常感谢。

**Comment by walkchen9** [comment]
已解决
