### ISSUE TITLE
Streaming did not end with [DONE] & [ALL DONE] + finish reason is not "stop"

### ISSUE THREAD

**Issue by bi1101** [acheong08/ChatGPT-to-API#14]
Hi thankyou for the project. I want to report some errors which make it unlike the officials api and, make it unsuable for streaming response when streaming set to "true"

I have attached the screenshot of the official response and the modded response for reference. Hop to here from you soon!
Official
![image](https://user-images.githubusercontent.com/15710921/237027737-911e3020-6d41-46c4-8f68-670f7acfba80.png)
from the modded API
![image](https://user-images.githubusercontent.com/15710921/237027827-b70ffdfc-8c46-4451-a3e8-f6f562109159.png)

**Comment by acheong08** [comment]
It does end with [DONE]. Just Checked.

As for the stop, it's not exactly necessary but I'll add it anyways

**Comment by bi1101** [comment]
Thanks for the reply, I checked it and realize it ends with [done] too, however further investigation found there are missing line breaks which prevents it being reconized by postman desktop app and my app also

**Comment by acheong08** [comment]
Fixed
