### ISSUE TITLE
[Error code 429] Too many requests in one hour

### ISSUE THREAD

**Issue by bi1101** [acheong08/ChatGPT-to-API#16]
Hi, I'm testing the server it works perfectly, so very thank you for your project!

However, I ecnouter the error 429 with the message "Too many requests in one hour"

After futher examination, this doesn't seem to be the problem with Open AI as the accounts still works as normal and after I reset the Docker container, everything works as normal.

I examined the code to try and find the limit but cannot find it. Hopes you can resolve this issues. Thank you!

**Comment by acheong08** [comment]
Rate limits seem to be applied per IP or based on fingerprint. I've encountered this issue but haven't been able to figure it out either

**Comment by bi1101** [comment]
Thankyou, I tried to use proxies and have not encountered the issue since then so I think you can add a note to readme if needed
