### ISSUE TITLE
Responses often get cut off

### ISSUE THREAD

**Issue by bi1101** [acheong08/ChatGPT-to-API#24]
Chat GPT seems to have limit the response length and added the "Continue generating" button which makes API calls get cut off
It would be nice to have a workaround.
![image](https://github.com/acheong08/ChatGPT-to-API/assets/15710921/90aff241-696f-4b6a-80a3-ab5d882e1c50)

**Comment by acheong08** [comment]
Done. It took a lot of refactoring

**Comment by bi1101** [comment]
Wowwwowowowowowoo
