### ISSUE TITLE
some bugs in authenticator and API

### ISSUE THREAD

**Issue by xixixi2000** [acheong08/ChatGPT-to-API#3]
1. in authenticator, got 429, but I got 200 when using a browser

Location: get_access_token
Status code: 429
Details: {"details":"Rate limit exceeded"}
Embedded error: error: Check details

2. in API, losing tailing 6 words in the response comparing with the webpage

ME: hello, how are you?
GPT: Hello! As an AI language model, I don't have feelings or emotions, but I'm functioning as intended and ready to assist you with any questions or tasks you may have. How can I assist you today?

{"id":"chatcmpl-WXlfa2FBbmROaXhpSUFyZUF3ZANvbWUF","object":"chat.completion","created":1681362002,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0},"choices":[{"index":0,"message":{"role":"assistant","content":"Hello! As an AI language model, I don't have feelings or emotions, but I'm functioning as intended and ready to assist you with any questions or tasks you may have."},"finish_reason":"stop"}]}

I try to open the log of the stream, and result of the stream is the same, also lack of the tailing words...

3. Difference with the official API, when using a "system" role, got 400 bad request, should use "user" instead?
4. a Parent_id and Conversation_id should be use to keep up with the thread ?

**Comment by acheong08** [comment]
> a Parent_id and Conversation_id should be use to keep up with the thread ?

No. Keep track of history on client side like you would with official API

**Comment by acheong08** [comment]
> in API, losing tailing 6 words in the response comparing with the webpage

Where are missing?

**Comment by xixixi2000** [comment]
> > in API, losing tailing 6 words in the response comparing with the webpage
> 
> Where are missing?

every response, lack of the tailing 6 words ... as the example I posted

**Comment by acheong08** [comment]
That is expected. GPT does not always generate a fixed response. Each response should be different.

**Comment by acheong08** [comment]
As for authenticator, I also get that with a VPS IP. You might need a residential proxy

**Comment by acheong08** [comment]
```json
{"id":"chatcmpl-QXlha2FBbmROaXhpZUFyZUF3ZXNvbWUK","object":"chat.completion","created":0,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0},"choices":[{"index":0,"message":{"role":"assistant","content":"Hello! As an AI language model, I don't have emotions like humans do, but I am functioning as intended and ready to assist you with any questions or tasks you have! How may I help you today?"},"finish_reason":"stop"}]}
```

**Comment by xixixi2000** [comment]
> > a Parent_id and Conversation_id should be use to keep up with the thread ?
> 
> No. Keep track of history on client side like you would with official API

yes, we can send a whole history to the server, but cannot send the system role, and the most important is , it generate many "New Chat" on the server :(

**Comment by acheong08** [comment]
I also fixed a few bugs today. Might help with cut off responses

**Comment by xixixi2000** [comment]
> As for authenticator, I also get that with a VPS IP. You might need a residential proxy

with email & pass pair? but I can get them using a browser, the same network

**Comment by acheong08** [comment]
> yes, we can send a whole history to the server, but cannot send the system role, and the most important is , it generate many "New Chat" on the server :(

Yes. That is indeed an issue. I recommend using some throwaway accounts with this that you don't usually use.

As for the system role, it was only patched after I open sourced this. OpenAI is watching

**Comment by xixixi2000** [comment]
> I also fixed a few bugs today. Might help with cut off responses if it did indeed have an effect in the past

Good news for it, I will try it later :)

**Comment by acheong08** [comment]
> with email & pass pair? but I can get them using a browser, the same network

Yes. They might be identifying it somehow. I am also using the same IP. Not sure why

**Comment by xixixi2000** [comment]
> > with email & pass pair? but I can get them using a browser, the same network
> 
> Yes. They might be identifying it somehow. I am also using the same IP. Not sure why

the auth steps are different?

**Comment by acheong08** [comment]
I tried to mimic the real auth as much as possible but there might be slight differences. It is overall impossible to completely imitate a browser.

**Comment by xixixi2000** [comment]
yes, but shall we use a node/js to do so? and combine into ur project

**Comment by xixixi2000** [comment]
> I also fixed a few bugs today. Might help with cut off responses if it did indeed have an effect in the past

How can I get the newest version？

**Comment by acheong08** [comment]
> > I also fixed a few bugs today. Might help with cut off responses if it did indeed have an effect in the past
> 
> How can I get the newest version？

`go install -u github.com/acheong08/ChatGPT-to-API@latest`

**Comment by acheong08** [comment]
> yes, but shall we use a node/js to do so? and combine into ur project

Node/JS is actually worse at mimicking a browser due to lack of good TLS spoofing libraries & low level control of fingerprinting.

**Comment by xixixi2000** [comment]
use a chrome paired with it ?

**Comment by acheong08** [comment]
The current implementation work with a good proxy. I don't feel the need for browser automation

**Comment by xixixi2000** [comment]
the authenticator works ! :) But can I use the microsoft auth account ? :)

**Comment by xixixi2000** [comment]
the new clone of [ChatGPT-to-API] does not work, got 401, and I changed back to the old one, got 200 (but lack of the tailing words)

**Comment by acheong08** [comment]
> the authenticator works ! :) But can I use the microsoft auth account ? :)

no :(

**Comment by acheong08** [comment]
> the new clone of [ChatGPT-to-API] does not work, got 401, and I changed back to the old one, got 200 (but lack of the tailing words)

works for me. Can you check the puid or access tokens?

**Comment by acheong08** [comment]
```bash
 $ curl http://127.0.0.1:8080/v1/chat/completions -d '{"messages":[{"role":"user", "content":"Hello, how are you?"}]}'
{"id":"chatcmpl-QXlha2FBbmROaXhpZUFyZUF3ZXNvbWUK","object":"chat.completion","created":0,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0},"choices":[{"index":0,"message":{"role":"assistant","content":"Hello! As an AI language model, I don't have emotions, but I'm functioning properly and ready to assist you. How can I help you today?"},"finish_reason":"stop"}]}%                                 [  9:13PM ]  [ acheong@InsignificantV3:~/Projects/freechatgpt(master✔) ]
 $ git pull
Already up to date.
```

**Comment by xixixi2000** [comment]
sorry, need a access_token.json this time :) ignore my auth in the header , works now :)
