### ISSUE TITLE
如何固定一个chat的channel？

### ISSUE THREAD

**Issue by aloasut** [acheong08/ChatGPT-to-API#30]
每次请求都创建一个 new Chat
另外，是否可以合并gpt4和gpt3.5？

**Comment by webs3c** [comment]
确实，现在每调用一次就创建一个新的会话，在语言翻译这种场景下就是我每翻译一次就会创建一个新的会话，导致账号被风控这是一个很大的问题。
但是可能考虑到多人使用场景下上下文的问题，所以建议出一个模式选择，是单会话持续调用还是每调用一次创建一个新的会话

**Comment by InterestingDarkness** [comment]
Does #35 match your need?

**Comment by InterestingDarkness** [comment]
> 确实，现在每调用一次就创建一个新的会话，在语言翻译这种场景下就是我每翻译一次就会创建一个新的会话，导致账号被风控这是一个很大的问题。 但是可能考虑到多人使用场景下上下文的问题，所以建议出一个模式选择，是单会话持续调用还是每调用一次创建一个新的会话

The previous context can be avoided by setting the parent_message_id to a "root" message.

**Comment by acheong08** [comment]
Can't be continuous as one of the features is managing history client side.
