### ISSUE TITLE
 Is ADMIN_PASSWORD similar to openai’s api_key?

### ISSUE THREAD

**Issue by aldington-david** [acheong08/ChatGPT-to-API#31]
Is ADMIN_PASSWORD similar to openai’s api_key?

**Comment by acheong08** [comment]
No. You set it yourself to authenticate actions like changing tokens live

**Comment by aldington-david** [comment]
> No. You set it yourself to authenticate actions like changing tokens live

So,there is no authentication measure to prevent abuse of the self api right?
I'm concerned that the API address might be captured by scanners like Censys when it's reverse proxied to port 443.

**Comment by acheong08** [comment]
> So,there is no authentication measure to prevent abuse of the self api right?
> I'm concerned that the API address might be captured by scanners like Censys when it's reverse proxied to port 443.

No. I made this as a free API for people to use. You will need to add your own middleware for API authentication

**Comment by acheong08** [comment]
A PR supported this iirc. Put in `api_keys.txt`
