### ISSUE TITLE
每次对话都会在帐号里产生一条新的聊天记录，是否能开启隐私模式？

### ISSUE THREAD

**Issue by yinm0591** [acheong08/ChatGPT-to-API#32]
将ChatGPT转换成API后，每次通过API对话都会在帐号里产生一条新的聊天记录。
是否能开启隐私模式？ 即： Setting -> Data controls -> 关闭 Chat history & training 的状态下进行对话。
谢谢~

**Comment by InterestingDarkness** [comment]
https://github.com/acheong08/ChatGPT-to-API/pull/35
Yes, and this does not affect account settings.

**Comment by yinm0591** [comment]
Could you please update the docker image, thanks

**Comment by acheong08** [comment]
Published
