### ISSUE TITLE
Why ignore custom access tokens?

### ISSUE THREAD

**Issue by InterestingDarkness** [acheong08/ChatGPT-to-API#38]
https://github.com/acheong08/ChatGPT-to-API/commit/9a295ce6fbf513e7f8e57ac00af31121f78e5c63
I think this feature would give the user easy control over what access token to use

**Comment by acheong08** [comment]
Sometimes people are required to set a token in some software so they set invalid fake token

**Comment by acheong08** [comment]
It will cause a lot of trouble for users of one of my services

**Comment by InterestingDarkness** [comment]
We could perhaps add a check here, such as checking whether it starts with "sk-"

**Comment by acheong08** [comment]
The access tokens should start with `eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9`

**Comment by acheong08** [comment]
Might be worthwhile
