### ISSUE TITLE
How to use it? i get 404 page not found

### ISSUE THREAD

**Issue by feiyu0** [acheong08/ChatGPT-to-API#4]
I build by docker.anything i get lost?

**Comment by acheong08** [comment]
POST request

**Comment by feiyu0** [comment]
可以具体一些吗？我用 Docker compose安装后，接下来应该怎样做可以正常进行调用呢

**Comment by skill7899** [comment]
i can not use , when i post request 

HTTP 500 Internal Server Error. The server had an error while processing your request, please try again.
See https://platform.openai.com/docs/guides/error-codes for more details.

{"error":"error sending request"}

**Comment by acheong08** [comment]
Need some more debug info. Might be helpful to add some print statements

**Comment by skill7899** [comment]
Access token retrieval has been automated: 
https://github.com/acheong08/ChatGPT-to-API/tree/master/tools/authenticator
i add my account accounts.txt and  touch access_tokens.txt authenticated_accounts.txt
docker buid 
i patch http://127.0.0.1:18080/admin/tokens 
it will response  Unauthorized

**Comment by acheong08** [comment]
There is authentication for admin stuff

**Comment by acheong08** [comment]
Default password is `TotallySecurePassword` put as `Authorization` header

**Comment by skill7899** [comment]
> Default password is `TotallySecurePassword` put as `Authorization` header

it's ok , thanks
