### ISSUE TITLE
how to proceed

### ISSUE THREAD

**Issue by linrb685** [acheong08/ChatGPT-to-API#42]
When a question outputs half of the answer result value, how to let him continue to output the second half? Send to continue and cannot continue

**Comment by acheong08** [comment]
Requires more research

**Comment by BlueSkyXN** [comment]
> When a question outputs half of the answer result value, how to let him continue to output the second half? Send to continue and cannot continue当一个问题输出答案结果值的一半时，如何让他继续输出后半部分？发送以继续，但无法继续

Check Token Limit and Network
