### ISSUE TITLE
no response a while then error 500

### ISSUE THREAD

**Issue by maminiainalaic** [acheong08/ChatGPT-to-API#43]
Jun 4 10:03:52 AM  2023/06/04 07:03:52 [Recovery] 2023/06/04 - 07:03:52 panic recovered:
Jun 4 10:03:52 AM  POST /v1/chat/completions HTTP/1.1
Jun 4 10:03:52 AM  [GIN] 2023/06/04 - 07:03:52 | 500 |         4m20s |   100.20.92.101 | POST     "/v1/chat/completions"
Jun 4 10:03:52 AM  Host: chathpt-to-api.onrender.com
Jun 4 10:03:52 AM  Accept: */*
Jun 4 10:03:52 AM  Accept-Encoding: gzip
Jun 4 10:03:52 AM  Cdn-Loop: cloudflare; subreqs=1
Jun 4 10:03:52 AM  Cf-Connecting-Ip: 100.20.92.101
Jun 4 10:03:52 AM  Cf-Ew-Via: 15
Jun 4 10:03:52 AM  Cf-Ipcountry: US
Jun 4 10:03:52 AM  Cf-Ray: 7d1e4b2b2156c3df-SEA
Jun 4 10:03:52 AM  Cf-Visitor: {"scheme":"https"}
Jun 4 10:03:52 AM  Cf-Worker: onrender.com
Jun 4 10:03:52 AM  Content-Length: 1830
Jun 4 10:03:52 AM  Content-Type: application/json
Jun 4 10:03:52 AM  Render-Proxy-Ttl: 4
Jun 4 10:03:52 AM  True-Client-Ip: 100.20.92.101
Jun 4 10:03:52 AM  User-Agent: python-requests/2.31.0
Jun 4 10:03:52 AM  X-Forwarded-For: 100.20.92.101, 172.71.151.78, 10.220.140.9
Jun 4 10:03:52 AM  X-Forwarded-Proto: https
Jun 4 10:03:52 AM  X-Request-Start: 1685861971737656
Jun 4 10:03:52 AM  
Jun 4 10:03:52 AM  
Jun 4 10:03:52 AM  runtime error: invalid memory address or nil pointer dereference
Jun 4 10:03:52 AM  /usr/local/go/src/runtime/panic.go:260 (0x44b0dc)
Jun 4 10:03:52 AM  /usr/local/go/src/runtime/signal_unix.go:837 (0x44b0ac)
Jun 4 10:03:52 AM  /app/handlers.go:107 (0x8c62d5)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8c7af5)
Jun 4 10:03:52 AM  /app/middleware.go:57 (0x8c7a4e)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8c77d7)
Jun 4 10:03:52 AM  /app/middleware.go:34 (0x8c77be)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8b0a01)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x8b09ec)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8afb26)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x8afb09)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8aebaa)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x8ae831)
Jun 4 10:03:52 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x8ae4dc)
Jun 4 10:03:52 AM  /usr/local/go/src/net/http/server.go:2936 (0x66a275)
Jun 4 10:03:52 AM  /usr/local/go/src/net/http/server.go:1995 (0x666af1)
Jun 4 10:03:52 AM  /usr/local/go/src/runtime/asm_amd64.s:1598 (0x467580)
Jun 4 10:03:52 AM  
Jun 4 10:07:21 AM  
Jun 4 10:07:21 AM  [GIN] 2023/06/04 - 07:07:21 | 500 |         4m21s |     41.77.19.29 | POST     "/v1/chat/completions"
Jun 4 10:07:21 AM  
Jun 4 10:07:21 AM  2023/06/04 07:07:21 [Recovery] 2023/06/04 - 07:07:21 panic recovered:
Jun 4 10:07:21 AM  POST /v1/chat/completions HTTP/1.1
Jun 4 10:07:21 AM  Host: chathpt-to-api.onrender.com
Jun 4 10:07:21 AM  Accept: */*
Jun 4 10:07:21 AM  Accept-Encoding: gzip
Jun 4 10:07:21 AM  Cdn-Loop: cloudflare; subreqs=1
Jun 4 10:07:21 AM  Cf-Connecting-Ip: 41.77.19.29
Jun 4 10:07:21 AM  Cf-Ew-Via: 15
Jun 4 10:07:21 AM  Cf-Ipcountry: MG
Jun 4 10:07:21 AM  Cf-Ray: 7d1e503c81b24fbd-JNB
Jun 4 10:07:21 AM  Cf-Visitor: {"scheme":"https"}
Jun 4 10:07:21 AM  Cf-Worker: onrender.com
Jun 4 10:07:21 AM  Content-Length: 117
Jun 4 10:07:21 AM  Content-Type: application/json
Jun 4 10:07:21 AM  Render-Proxy-Ttl: 4
Jun 4 10:07:21 AM  True-Client-Ip: 41.77.19.29
Jun 4 10:07:21 AM  User-Agent: curl/7.88.1
Jun 4 10:07:21 AM  X-Forwarded-For: 41.77.19.29, 197.234.243.29, 10.220.86.174
Jun 4 10:07:21 AM  X-Forwarded-Proto: https
Jun 4 10:07:21 AM  X-Request-Start: 1685862180122486
Jun 4 10:07:21 AM  
Jun 4 10:07:21 AM  
Jun 4 10:07:21 AM  runtime error: invalid memory address or nil pointer dereference
Jun 4 10:07:21 AM  /usr/local/go/src/runtime/panic.go:260 (0x44b0dc)
Jun 4 10:07:21 AM  /usr/local/go/src/runtime/signal_unix.go:837 (0x44b0ac)
Jun 4 10:07:21 AM  /app/handlers.go:107 (0x8c62d5)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8c7af5)
Jun 4 10:07:21 AM  /app/middleware.go:57 (0x8c7a4e)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8c77d7)
Jun 4 10:07:21 AM  /app/middleware.go:34 (0x8c77be)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8b0a01)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x8b09ec)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8afb26)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x8afb09)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x8aebaa)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x8ae831)
Jun 4 10:07:21 AM  /go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x8ae4dc)
Jun 4 10:07:21 AM  /usr/local/go/src/net/http/server.go:2936 (0x66a275)
Jun 4 10:07:21 AM  /usr/local/go/src/net/http/server.go:1995 (0x666af1)
Jun 4 10:07:21 AM  /usr/local/go/src/runtime/asm_amd64.s:1598 (0x467580)

**Comment by maminiainalaic** [comment]
on local it raises: curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number

**Comment by BlueSkyXN** [comment]
> on local it raises: curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number在本地，它会引起：curl：（35）OpenSSL/3.0.8：错误：0A 00010 B：SSL例程：：错误的版本号

Are you using Docker or the compiled binary file?

**Comment by acheong08** [comment]
> on local it raises: curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number

Looks like you tried to use https when it's http

**Comment by maminiainalaic** [comment]
> > on local it raises: curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number
> 
> Looks like you tried to use https when it's http

no it's https (my server)

**Comment by acheong08** [comment]
well, it's something wrong on your end.

Try setting it as http and passing it through cloudflare for https
