### ISSUE TITLE
能否发现回复被截断后自动发送continue

### ISSUE THREAD

**Issue by yinm0591** [acheong08/ChatGPT-to-API#47]
chatgpt web回答内容过长，会先返回一部分，然后点击continue再返回一部分，再点击contine再返回一部分。continue是基于conversation_id的，转换成api后就无法有效的continue了。Chat-to-API能否发现回复被截断后自动发送continue。
(PS. 偶尔也遇到chatgpt的continue出问题可以无限continue，可以设定一个上限，例如最多continue 3次)

谢谢~

**Comment by acheong08** [comment]
Already implemented in revChatGPT. Will port this over to ChatGPT-to-API when I get time
Notes:
https://github.com/acheong08/ChatGPT/blob/74b32a02a16a852dac705d0844943b486fcb7cf8/src/revChatGPT/V1.py#L567C5-L649

**Comment by bi1101** [comment]
I can confirm this is not a problem with the max token value, this is implemented on the web version and you have to click continue to resume the response when the response are long.

**Comment by acheong08** [comment]
> I can confirm this is not a problem with the max token value, this is implemented on the web version and you have to click continue to resume the response when the response are long.

I mean you can detect when continue button is available via that field

**Comment by acheong08** [comment]
Done

**Comment by yinm0591** [comment]
这个功能太棒了。
