### ISSUE TITLE
Proposal for Chat ID Selection Mode for Persistent Sessions

### ISSUE THREAD

**Issue by uxfion** [acheong08/ChatGPT-to-API#49]
> Firstly, I would like to express my sincere admiration for your outstanding project. It has been of great utility and has significantly improved the efficiency of my tasks.

I believe there is a necessity to offer a mode to select and persist a Chat ID, This has been mentioned in previous issues https://github.com/acheong08/ChatGPT-to-API/issues/30. I suggest providing a mode selection feature as follows:

**1. Single Session Mode: Choose a Chat ID and continuously call it.
2. New Session Mode: Create a new session for every call.**

For the Single Session Mode, I have specific use cases. I would like to pre-establish a few conversations with specific functionalities. By providing prompts to the model, certain conversations can maintain functionality such as translation or terminal simulation. This approach would make API calls to different Chat IDs much more convenient and provide specific features.

I look forward to your thoughts on this suggestion and I appreciate your consideration.

**Comment by acheong08** [comment]
The official API allows you to handle conversation history on the client side. How do you propose to deal with this when you are stuck on a single session (which handles conversation history server side)

**Comment by uxfion** [comment]
I don't quite understand "When you get stuck on a single session (which handles the server-side conversation history), how do you plan to handle it?"

**Comment by acheong08** [comment]
The goal of this repo is to replicate the official API where conversation history is managed client side:

When you send a request, all previous messages are part of the messages array. You can modify previous messages and it would still work.

However, if you use a single persistent session, conversations are handled server side by OpenAI

**Comment by uxfion** [comment]
I got it, the purpose of this repository is to replicate the official API while allowing control conversation history on our own service.

**Comment by uxfion** [comment]
So, how can we avoid leaving the conversation on the web page while making a request?

**Comment by acheong08** [comment]
That should be the default

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-to-API/blob/a02690a080d7894d0a56af4980b5a899b653c864/internal/chatgpt/typings.go#L33

**Comment by uxfion** [comment]
Thank you for answering my questions. I really like this project and I will close this issue myself.

**Comment by uxfion** [comment]
> https://github.com/acheong08/ChatGPT-to-API/blob/a02690a080d7894d0a56af4980b5a899b653c864/internal/chatgpt/typings.go#L33

I have tested and found that the latest docker image still retains conversation history, including the self-build Dockerfile.

**Comment by acheong08** [comment]
Wait for https://github.com/acheong08/ChatGPT-to-API/actions/runs/5221708494

**Comment by uxfion** [comment]
<img width="1575" alt="image" src="https://github.com/acheong08/ChatGPT-to-API/assets/44778029/320539a5-e05b-49c6-94d8-b7dac18d8571">
It still leave the  conversation history.
Did I set it wrong

**Comment by acheong08** [comment]
Try printing the payload from Go and see what is going on

**Comment by uxfion** [comment]
Sorry, I am new to go lang, and also I can't connect to the Scratch container because there is no shell available in the Scratch container.

Would you mind testing the newly released Docker on your local machine? I'm not sure if it's due to the release or my own settings.
