### ISSUE TITLE
401 Error sending request

### ISSUE THREAD

**Issue by tmkmch** [acheong08/ChatGPT-to-API#5]
Yesterday it worked normally without errors.

Today there's error 401 when sending request.

[GIN-debug] GET    /ping                     --> main.main.func1 (4 handlers)
[GIN-debug] PATCH  /admin/puid               --> main.puidHandler (5 handlers)
[GIN-debug] PATCH  /admin/password           --> main.passwordHandler (5 handlers)
[GIN-debug] PATCH  /admin/tokens             --> main.tokensHandler (6 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> main.optionsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> main.nightmare (4 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 0.0.0.0:6541
[GIN] 2023/04/15 - 19:02:52 | 200 |       276.6µs |             ::1 | OPTIONS  "/v1/chat/completions"
API_REVERSE_PROXY set:https://bypass.churchless.tech/api/conversation
[GIN] 2023/04/15 - 19:02:53 | 401 |    960.8103ms |             ::1 | POST     "/v1/chat/completions"

Is it related to closing completions endpoint by OpenAI?

**Comment by acheong08** [comment]
PUID also closed. I'm working on alternative.

**Comment by acheong08** [comment]
Fixed
