### ISSUE TITLE
It is not possible to support multiple concurrent requests at the same time as the official API

### ISSUE THREAD

**Issue by disingn** [acheong08/ChatGPT-to-API#53]
Hey man, this project is really good, but after my local deployment test he is normal, but when I try multiple concurrent requests for my deployed api it does report an error and it tells me "Only one message at a time." Please allow any other responses to complete before sending another message, or wait one minute.” How do you need to solve this?

**Comment by oldweipro** [comment]
Multiple accounts loop.

**Comment by disacolr** [comment]
> 多个帐户循环。



> Multiple accounts loop.

There's no better way than that？？

**Comment by acheong08** [comment]
It can, you can have however many concurrent requests as you have accounts. I have instance running with 300 accounts → 300 concurrent requests
