### ISSUE TITLE
issues Sorry, you have been blocked

### ISSUE THREAD

**Issue by YoungBreezeM** [acheong08/ChatGPT-to-API#56]
我的 vps 通过浏览器访问 https://chat.openai.com ip 不会被屏蔽，但是使用这个项目的api 做转发就会出现  error 500 Sorry, you have been blocked. 请问是什么原因导致的。

**Comment by YoungBreezeM** [comment]
issues 已解决

**Comment by bi1101** [comment]
你是如何解决的？你可以分享一下吗？

**Comment by acheong08** [comment]
https://github.com/acheong08/funcaptcha

**Comment by acheong08** [comment]
Need to update some code

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-to-API/releases/tag/1.5.2
