### ISSUE TITLE
add plugin api

### ISSUE THREAD

**Issue by roodkcab** [acheong08/ChatGPT-to-API#59]
model support gpt-4-plugins, but plugin_ids can't pass to openai.

**Comment by roodkcab** [comment]
I added plugin_ids parameter to both api and chatapi, works fine. I'll submit a pr laster. 

by the way, openai release function calling api this morning. looks yummy.

**Comment by acheong08** [comment]
> by the way, openai release function calling api this morning. looks yummy.

Only for official API.
