### ISSUE TITLE
API_REVERSE_PROXY="https://bypass.churchless.tech/api/conversation"

### ISSUE THREAD

**Issue by hcr707305003** [acheong08/ChatGPT-to-API#6]
Bad gateway Error code 502

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`

**Comment by acheong08** [comment]
`export API_REVERSE_PROXY="https://chat.gateway.do/api/conversation"`

**Comment by hcr707305003** [comment]
> `export API_REVERSE_PROXY="https://chat.gateway.do/api/conversation"`

thank

**Comment by hcr707305003** [comment]
https://chat.gateway.do/api/conversation

> > `export API_REVERSE_PROXY="https://chat.gateway.do/api/conversation"`
> 
> thank



> `export API_REVERSE_PROXY="https://chat.gateway.do/api/conversation"`

"https://chat.gateway.do/api/conversation" can`t request

**Comment by acheong08** [comment]
`export API_REVERSE_PROXY="https://ai.fakeopen.com/api/conversation"`

**Comment by acheong08** [comment]
OpenAI issued a takedown request today morning to the other API
