### ISSUE TITLE
While using openai-translator, I can't get the result

### ISSUE THREAD

**Issue by Geniucker** [acheong08/ChatGPT-to-API#60]
After I press translate, the console shows 200 but there's no result in the [openai-translator](https://github.com/openai-translator/openai-translator)

**Comment by acheong08** [comment]
Show stream

**Comment by Geniucker** [comment]
![image](https://github.com/acheong08/ChatGPT-to-API/assets/61449208/ed4dbde3-ab6d-4cc1-af5d-fa02962085ce)
the corresponding line is marked in red
