### ISSUE TITLE
The response get cut off with the latest release

### ISSUE THREAD

**Issue by bi1101** [acheong08/ChatGPT-to-API#65]
With the previous release, the response cut off has been fixed, however, with this release, this "quirks" came back

**Comment by UseLEss213** [comment]
hey bill, can u tell me why it shows error 404 page not found when i run this - http://127.0.0.1:8080/v1/chat/completions , in terminal everything is ok, now how to get the endpoint url and key?

**Comment by acheong08** [comment]
> With the previous release, the response cut off has been fixed, however, with this release, this "quirks" came back

What's the quirk?

**Comment by bi1101** [comment]
> > With the previous release, the response cut off has been fixed, however, with this release, this "quirks" came back
> 
> What's the quirk?

The fact that long response gets cut off (like with the Chat GPT webpage you have to hit continue response)

**Comment by acheong08** [comment]
Auto continue is still enabled
