### ISSUE TITLE
Authentication by "continue by google"

### ISSUE THREAD

**Issue by zeitamin** [acheong08/ChatGPT-to-API#66]
seems the only supported auth is via user and password, is this right? the first thing I do after running is as follows which result in unauthorized:

```
# curl -X PATCH -H "Content-Type: application/json" -d '{"puid":"my puid key"}' http://127.0.0.1:8080/admin/puid
Unauthorized
```

**Comment by acheong08** [comment]
Default password for admin is `TotallySecurePassword`

**Comment by acheong08** [comment]
> seems the only supported auth is via user and password

yes
