### ISSUE TITLE
ERROR 413

### ISSUE THREAD

**Issue by maminiainalaic03** [acheong08/ChatGPT-to-API#67]
Jun 18 03:15:52 PM  [GIN] 2023/06/18 - 12:15:52 | 413 |  433.574605ms |  54.187.200.255 | POST     "/v1/chat/completions"

**Comment by acheong08** [comment]
Too many tokens

**Comment by maminiainalaic03** [comment]
I uploaded only 4

**Comment by maminiainalaic03** [comment]
> Too many tokens

I uploaded only 4

**Comment by maminiainalaic03** [comment]
@acheong08 
and what about this:

Jun 18 05:00:13 PM  Failed to parse JSON
Jun 18 05:00:13 PM   ping
Jun 18 05:00:13 PM  
Jun 18 05:00:13 PM  Failed to parse JSON
Jun 18 05:00:13 PM  2023-06-18 14:00:13.219956

**Comment by acheong08** [comment]
That is expected and doesn't actually cause any harm
