### ISSUE TITLE
 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Beckjiang** [acheong08/ChatGPT-to-API#7]
When I use reverse proxy, I get the following debug error below:

`{"error":"error sending requestPost \"https://bypass.churchless.tech/api/conversation\": x509: certificate signed by unknown authority"}`

**Comment by Beckjiang** [comment]
I built and ran a program using Docker on macOS, and I have already trusted GTS Root R1 in the keychain.

**Comment by acheong08** [comment]
> When I use reverse proxy, I get the following debug error below:
> 
> `{"error":"error sending requestPost \"https://bypass.churchless.tech/api/conversation\": x509: certificate signed by unknown authority"}`

1. Try `https://bypass.churchless.tech/conversation` or `https://ai.fakeopen.com/api/conversation`
2. Install ca-certificates or disable SSL verification
