### ISSUE TITLE
ChatGPT-to-API and ChatGPT-Proxy-V4

### ISSUE THREAD

**Issue by YOMIkio** [acheong08/ChatGPT-to-API#72]
What is the difference between ChatGPT-to-API project and ChatGPT-Proxy-V4 project, it seems to me that the functions are similar

**Comment by YOMIkio** [comment]
ChatGPT-Proxy-V4 only has web proxy, while ChatGPT-to-API contains both web and api proxies?

**Comment by acheong08** [comment]
ChatGPT-Proxy-V4 is extremely simple, 
```
user ←→ proxy ←→ chat.openai.com
```

ChatGPT-to-API tries to maintain compatibility with the official OpenAI API so you can plug and play on different libraries that utilize the official API.
