### ISSUE TITLE
请问如何添加多个access_tokens

### ISSUE THREAD

**Issue by LNpks** [acheong08/ChatGPT-to-API#75]
请问如何添加多个access_tokens，来实现并发。在access_tokens.json中直接换行添加发现只能使用第一个

**Comment by LNpks** [comment]
> 
请问是在access_tokens.json里面放多个tokens吗，具体格式是怎么样的，我尝试了几种格式但是尝试并发请求时只能请求第一个账号

**Comment by LNpks** [comment]
。

**Comment by LNpks** [comment]
ttt

**Comment by LNpks** [comment]
感谢

> [ "accessToken1", "accessToken2", ..... ]

**Comment by LNpks** [comment]
> [ "accessToken1", "accessToken2", ..... ]

想再问一个问题，如果要自定义api key的话，看之前的issuse说要自定义api_keys.txt文件，但是如何自定义呢？

**Comment by acheong08** [comment]
in `api_keys.txt`:
```
apikey1
apikey2
...
```

**Comment by LNpks** [comment]
> in `api_keys.txt`:
> 
> ```
> apikey1
> apikey2
> ...
> ```

api_keys.txt需要放在哪里？是在根目录下自己打包镜像，还是修改docker-compose 映射进去（不知道目录是什么），感谢作者大大

**Comment by Cp0204** [comment]
> > in `api_keys.txt`:
> > ```
> > apikey1
> > apikey2
> > ...
> > ```
> 
> api_keys.txt需要放在哪里？是在根目录下自己打包镜像，还是修改docker-compose 映射进去（不知道目录是什么），感谢作者大大

同问，解决了吗
