### ISSUE TITLE
Socks5h proxy support.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT-to-API#78]
The documentation on [Environment variables](https://github.com/acheong08/ChatGPT-to-API/#environment-variables) tells the following:

![image](https://github.com/acheong08/ChatGPT-to-API/assets/11155854/a640d4a5-c09f-47cd-8faf-14371a716cff)

I would like to know whether the socks5h proxy, aka `socks5h://HOST:PORT`, is also supported.

Regards,
Zhao

**Comment by acheong08** [comment]
socks5h should work

**Comment by hongyi-zhao** [comment]
Why do you say so?

**Comment by acheong08** [comment]
I tested it and no errors were thrown
